[package]
name = "listing_nested_storage_mapping"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.10.1"

[dev-dependencies]
snforge_std = "0.38.0"
assert_macros = "2.10.1"

[scripts]
test = "snforge test"
