name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup all dependencies in one go
      - uses: ./.github/workflows/common-setup.yml

      # Run all verification tasks in parallel
      - name: Run verifications
        run: |
          echo "::group::Build and verify book"
          mdbook build -d book
          echo "::endgroup::"

          echo "::group::Verify cairo-listings"
          cargo install --path cairo-listings --locked
          cairo-listings verify >> $GITHUB_STEP_SUMMARY
          echo "::endgroup::"

          echo "::group::Check for typos"
          cargo install typos-cli
          typos
          echo "::endgroup::"
