name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/common-setup.yml

  verify:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build book
        run: mdbook build -d book

      - name: Install and run cairo-listings
        run: |
          cargo install --path cairo-listings --locked
          cairo-listings verify >> $GITHUB_STEP_SUMMARY

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
