name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  # First call the reusable workflow as a job
  setup:
    uses: ./.github/workflows/common-setup.yml

  # Then use it as a dependency for our verify job
  verify:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Verification steps (after setup is complete)
      - name: Run verifications
        run: |
          echo "::group::Build and verify book"
          mdbook build -d book
          echo "::endgroup::"

          echo "::group::Verify cairo-listings"
          cargo install --path cairo-listings --locked
          cairo-listings verify >> $GITHUB_STEP_SUMMARY
          echo "::endgroup::"

          echo "::group::Check for typos"
          cargo install typos-cli
          typos
          echo "::endgroup::"
