name: Build and Release mdbook

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Install mdbook
        uses: ./.github/workflows/install-mdbook

      - name: Build book (English)
        run: mdbook build -d book

      - name: Create ZIP file
        run: zip -r markdown-output.zip book/markdown

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: markdown-output.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
